<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>userlist</title>
</head>
<body>
<table>
    <thead>
    <tr>
        <td>日期</td>
        <td>销售额</td>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>2019-01-01</td>
        <td>100.0</td>
    </tr>
    <tr>
        <td>2019-01-02</td>
        <td>120.0</td>
    </tr>
    <tr>
        <td>2019-01-03</td>
        <td>130.0</td>
    </tr>
    <tr>
        <td>2019-01-04</td>
        <td>140.0</td>
    </tr>
    </tbody>
</table>
</body>
</html>
